//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SendDokumenter.iis.DocumentDataReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AttachedDocuments", Namespace="http://schemas.datacontract.org/2004/07/DigitalPostWcfService")]
    [System.SerializableAttribute()]
    public partial class AttachedDocuments : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SendDokumenter.iis.DocumentDataReference.AttachedFile[] AttachedFilesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmneordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MedlemsnummerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrganizationUnitNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrimaryClassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductionUnitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SagsnummerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecondaryClassField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SendDokumenter.iis.DocumentDataReference.AttachedFile[] AttachedFiles {
            get {
                return this.AttachedFilesField;
            }
            set {
                if ((object.ReferenceEquals(this.AttachedFilesField, value) != true)) {
                    this.AttachedFilesField = value;
                    this.RaisePropertyChanged("AttachedFiles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAddress {
            get {
                return this.EmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAddressField, value) != true)) {
                    this.EmailAddressField = value;
                    this.RaisePropertyChanged("EmailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Emneord {
            get {
                return this.EmneordField;
            }
            set {
                if ((object.ReferenceEquals(this.EmneordField, value) != true)) {
                    this.EmneordField = value;
                    this.RaisePropertyChanged("Emneord");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Medlemsnummer {
            get {
                return this.MedlemsnummerField;
            }
            set {
                if ((this.MedlemsnummerField.Equals(value) != true)) {
                    this.MedlemsnummerField = value;
                    this.RaisePropertyChanged("Medlemsnummer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrganizationUnitName {
            get {
                return this.OrganizationUnitNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OrganizationUnitNameField, value) != true)) {
                    this.OrganizationUnitNameField = value;
                    this.RaisePropertyChanged("OrganizationUnitName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrimaryClass {
            get {
                return this.PrimaryClassField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimaryClassField, value) != true)) {
                    this.PrimaryClassField = value;
                    this.RaisePropertyChanged("PrimaryClass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductionUnit {
            get {
                return this.ProductionUnitField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductionUnitField, value) != true)) {
                    this.ProductionUnitField = value;
                    this.RaisePropertyChanged("ProductionUnit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sagsnummer {
            get {
                return this.SagsnummerField;
            }
            set {
                if ((object.ReferenceEquals(this.SagsnummerField, value) != true)) {
                    this.SagsnummerField = value;
                    this.RaisePropertyChanged("Sagsnummer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecondaryClass {
            get {
                return this.SecondaryClassField;
            }
            set {
                if ((object.ReferenceEquals(this.SecondaryClassField, value) != true)) {
                    this.SecondaryClassField = value;
                    this.RaisePropertyChanged("SecondaryClass");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AttachedFile", Namespace="http://schemas.datacontract.org/2004/07/DigitalPostWcfService")]
    [System.SerializableAttribute()]
    public partial class AttachedFile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] DocumentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Document {
            get {
                return this.DocumentField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentField, value) != true)) {
                    this.DocumentField = value;
                    this.RaisePropertyChanged("Document");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DocumentDataReference.IDocumentData")]
    public interface IDocumentData {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentData/SendAttachments", ReplyAction="http://tempuri.org/IDocumentData/SendAttachmentsResponse")]
        string SendAttachments(SendDokumenter.iis.DocumentDataReference.AttachedDocuments attachment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentData/SendAttachments", ReplyAction="http://tempuri.org/IDocumentData/SendAttachmentsResponse")]
        System.Threading.Tasks.Task<string> SendAttachmentsAsync(SendDokumenter.iis.DocumentDataReference.AttachedDocuments attachment);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDocumentDataChannel : SendDokumenter.iis.DocumentDataReference.IDocumentData, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DocumentDataClient : System.ServiceModel.ClientBase<SendDokumenter.iis.DocumentDataReference.IDocumentData>, SendDokumenter.iis.DocumentDataReference.IDocumentData {
        
        public DocumentDataClient() {
        }
        
        public DocumentDataClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DocumentDataClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentDataClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentDataClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SendAttachments(SendDokumenter.iis.DocumentDataReference.AttachedDocuments attachment) {
            return base.Channel.SendAttachments(attachment);
        }
        
        public System.Threading.Tasks.Task<string> SendAttachmentsAsync(SendDokumenter.iis.DocumentDataReference.AttachedDocuments attachment) {
            return base.Channel.SendAttachmentsAsync(attachment);
        }
    }
}
